### ISSUE TITLE
Addresses on the item details page

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/eventsManualPlugin#10]
Addresses on the item details page should be clickable and should pull from primary links and buttons

**Comment by kmtabish** [comment]
Fixed, Please review.

**Comment by nathankeating** [comment]
I see that it is fixed on item details layout 1, but not on layouts 2 and 3

**Comment by sakshityagi** [comment]
@nathankeating Just tested on int server for all 4 layouts. Worked for me. Might be some caching issue. Please try again and let me know if it still doesn't work.

**Comment by nathankeating** [comment]
Confirmed
