### ISSUE TITLE
When it is an all day event, “All Day” should show below the event title in the list

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/eventsManualPlugin#13]
When it is an all day event, “All Day” should show below the event title in the list

The first event here is an all day event. It should show "All Day" underneath the title like where the time is for the second event
<img width="358" alt="screen shot 2015-10-14 at 12 46 51 am" src="https://cloud.githubusercontent.com/assets/6145369/10477687/14036306-720d-11e5-88a8-fe70c2c07cc3.png">

**Comment by kmtabish** [comment]
Fixed. Please review.

**Comment by nathankeating** [comment]
Confirmed
