### ISSUE TITLE
Switching to a new layout issue

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/eventsManualPlugin#14]
When you select a new item details layout, the UI in the emulator gets messed up.

This is an image of what the emulator looks like after I have switched from one layout to another:
<img width="364" alt="screen shot 2015-10-14 at 12 57 00 am" src="https://cloud.githubusercontent.com/assets/6145369/10477880/942b57ea-720e-11e5-84bd-1047f5440db9.png">

**Comment by kmtabish** [comment]
Fixed. Please review.

**Comment by nathankeating** [comment]
confirmed
