### ISSUE TITLE
"No events found" on the phone even though there are events

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/eventsManualPlugin#18]
"No events found" on the phone even though there are events.

This is only on the phone (I am running iOS 9). The CP emulator seems to work fine.

Phone screenshot:
![img_8699](https://cloud.githubusercontent.com/assets/6145369/10556075/50504e7c-742f-11e5-9d94-699f1904a35b.PNG)

CP Screenshot:
<img width="393" alt="screen shot 2015-10-16 at 5 57 20 pm" src="https://cloud.githubusercontent.com/assets/6145369/10556077/5bc8d684-742f-11e5-8c8e-6e5393058b74.png">

**Comment by sakshityagi** [comment]
This is fixed now. Please review.

**Comment by nathankeating** [comment]
Confirmed
