### ISSUE TITLE
List image should be a recommended size of 500px by 500px

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/eventsManualPlugin#8]
List image should be a recommended size of 500px by 500px

<img width="366" alt="screen shot 2015-10-13 at 11 45 43 pm" src="https://cloud.githubusercontent.com/assets/6145369/10476652/8c84627a-7204-11e5-828d-d335589daae4.png">

**Comment by kmtabish** [comment]
Fixed. Please review.

**Comment by nathankeating** [comment]
Confirmed, but please update this to be a square so that it represents the 500 by 500 dimensions appropriately

**Comment by nathankeating** [comment]
confirmed
